"""Full-text discovery orchestration, route resolution, acquisition, and validation."""

from aletheia_nexus.acquire.fulltext.exceptions import (
    AcquisitionAccessBlockedError,
    AcquisitionAuthRequiredError,
    AcquisitionError,
    AcquisitionNetworkError,
    AcquisitionNotFoundError,
    AcquisitionRateLimitError,
    AcquisitionRedirectError,
    AcquisitionRequestError,
    AcquisitionServiceError,
    AcquisitionTooLargeError,
    AcquisitionUnsafeUrlError,
)
from aletheia_nexus.acquire.fulltext.models import (
    AcquisitionResult,
    AcquisitionStatus,
    DocumentRole,
    IdentityStatus,
    IdentityValidationReport,
    PdfValidationReport,
    RedirectHop,
    RetrievedResource,
)
from aletheia_nexus.acquire.fulltext.orchestration import (
    DEFAULT_MAX_FILE_ATTEMPTS,
    DEFAULT_MAX_ROUTE_ATTEMPTS,
    FileAttempt,
    FileCandidateOrigin,
    FullTextAcquisitionStatus,
    MultiRouteAcquisitionResult,
    RouteAttempt,
    RouteCandidateOrigin,
    TitleSource,
    acquire_from_discovery,
    acquire_full_text,
)
from aletheia_nexus.acquire.fulltext.resolution import (
    DerivationMethod,
    DerivedFullTextCandidate,
    PageIdentityReport,
    PageType,
    ResolutionStatus,
    RetrievedPage,
    RouteResolutionResult,
    resolve_full_text_route,
)
from aletheia_nexus.acquire.fulltext.service import acquire_direct_pdf

__all__ = [
    "AcquisitionAccessBlockedError",
    "AcquisitionAuthRequiredError",
    "AcquisitionError",
    "AcquisitionNetworkError",
    "AcquisitionNotFoundError",
    "AcquisitionRateLimitError",
    "AcquisitionRedirectError",
    "AcquisitionRequestError",
    "AcquisitionResult",
    "AcquisitionServiceError",
    "AcquisitionStatus",
    "AcquisitionTooLargeError",
    "AcquisitionUnsafeUrlError",
    "DEFAULT_MAX_FILE_ATTEMPTS",
    "DEFAULT_MAX_ROUTE_ATTEMPTS",
    "DerivationMethod",
    "DerivedFullTextCandidate",
    "DocumentRole",
    "FileAttempt",
    "FileCandidateOrigin",
    "FullTextAcquisitionStatus",
    "IdentityStatus",
    "IdentityValidationReport",
    "MultiRouteAcquisitionResult",
    "PageIdentityReport",
    "PageType",
    "PdfValidationReport",
    "RedirectHop",
    "ResolutionStatus",
    "RetrievedPage",
    "RetrievedResource",
    "RouteAttempt",
    "RouteCandidateOrigin",
    "RouteResolutionResult",
    "TitleSource",
    "acquire_direct_pdf",
    "acquire_from_discovery",
    "acquire_full_text",
    "resolve_full_text_route",
]
