"""Full-text route resolution, acquisition, and validation for Aletheia Nexus."""

from aletheia_nexus.acquire.fulltext.exceptions import (
    AcquisitionAccessBlockedError,
    AcquisitionAuthRequiredError,
    AcquisitionError,
    AcquisitionNetworkError,
    AcquisitionNotFoundError,
    AcquisitionRateLimitError,
    AcquisitionRedirectError,
    AcquisitionRequestError,
    AcquisitionServiceError,
    AcquisitionTooLargeError,
    AcquisitionUnsafeUrlError,
)
from aletheia_nexus.acquire.fulltext.models import (
    AcquisitionResult,
    AcquisitionStatus,
    DocumentRole,
    IdentityStatus,
    IdentityValidationReport,
    PdfValidationReport,
    RedirectHop,
    RetrievedResource,
)
from aletheia_nexus.acquire.fulltext.resolution import (
    DerivationMethod,
    DerivedFullTextCandidate,
    PageIdentityReport,
    PageType,
    ResolutionStatus,
    RetrievedPage,
    RouteResolutionResult,
    resolve_full_text_route,
)
from aletheia_nexus.acquire.fulltext.service import acquire_direct_pdf

__all__ = [
    "AcquisitionAccessBlockedError",
    "AcquisitionAuthRequiredError",
    "AcquisitionError",
    "AcquisitionNetworkError",
    "AcquisitionNotFoundError",
    "AcquisitionRateLimitError",
    "AcquisitionRedirectError",
    "AcquisitionRequestError",
    "AcquisitionResult",
    "AcquisitionServiceError",
    "AcquisitionStatus",
    "AcquisitionTooLargeError",
    "AcquisitionUnsafeUrlError",
    "DerivationMethod",
    "DerivedFullTextCandidate",
    "DocumentRole",
    "IdentityStatus",
    "IdentityValidationReport",
    "PageIdentityReport",
    "PageType",
    "PdfValidationReport",
    "RedirectHop",
    "ResolutionStatus",
    "RetrievedPage",
    "RetrievedResource",
    "RouteResolutionResult",
    "acquire_direct_pdf",
    "resolve_full_text_route",
]
